### ISSUE TITLE
QR code working 

### ISSUE THREAD

**Issue by Kumaravinash9** [RetroShare/retroshare-mobile#11]

**Comment by defnax** [comment]
im not sure if short invite will work on mobile rs, to get connected?
on desktop rs often not works short invites

**Comment by Kumaravinash9** [comment]
> im not sure if short invite will work on mobile rs, to get connected?
> on desktop rs often not works short invites

Then if short invites feature will not work then i will add the QR code feature at that place.

**Comment by Kumaravinash9** [comment]
Related Plugin: https://pub.dev/packages/qr_code_scanner
