### ISSUE TITLE
UI need to be improved as well as Add friend feature is not working properly

### ISSUE THREAD

**Issue by Kumaravinash9** [RetroShare/retroshare-mobile#6]
![WhatsApp Image 2021-06-08 at 23 21 22](https://user-images.githubusercontent.com/64456168/121234186-0eeb4b80-c8b1-11eb-8e48-5fcef0f488ad.jpeg)

**Comment by Kumaravinash9** [comment]
Hello @defnax, I need you help in finding the better UI for the screen. Actually i have bad sense of UI. It would be great f you help me. Thanks

**Comment by Kumaravinash9** [comment]
Related issue : Show the avatar on the notifications

**Comment by defnax** [comment]
Hi but im not sure if the new invite will work on rs mobile version?
on desktop there are issues with short invites when no tor is used, 
Often not works to get connected via retroshare id
