### ISSUE TITLE
we are not able to send images in chat 

### ISSUE THREAD

**Issue by Kumaravinash9** [RetroShare/retroshare-mobile#8]
![WhatsApp Image 2021-06-09 at 17 23 07](https://user-images.githubusercontent.com/64456168/121353926-0136d400-c94c-11eb-8589-273bfe493dc8.jpeg)

**Comment by defnax** [comment]
you has merged now the changes from b1irds **feature-emoji-support** branch on master?

**Comment by Kumaravinash9** [comment]
> you has merged now the changes from b1irds **feature-emoji-support** branch on master?

I didn't  pull the emoji support. Actually i planned to push these changes along with image support.
